export const GET_ALL_MENU_REQUEST = "GET_ALL_MENU_REQUEST";

export const GET_ALL_MENU_SUCCESS = "GET_ALL_MENU_SUCCESS";

export const GET_ALL_MENU_FAILURE = "GET_ALL_MENU_FAILURE";

export const GET_ALL_CHILDREN_REQUEST = "GET_ALL_CHILDREN_REQUEST";

export const GET_ALL_CHILDREN_SUCCESS = "GET_ALL_CHILDREN_SUCCESS";

export const GET_ALL_CHILDREN_FAILURE = "GET_ALL_CHILDREN_FAILURE";

export const GET_ALL_CATEGORY_DATA_REQUEST = "GET_ALL_CATEGORY_DATA_REQUEST";

export const GET_ALL_CATEGORY_DATA_SUCCESS = "GET_ALL_CATEGORY_DATA_SUCCESS";

export const GET_ALL_CATEGORY_DATA_FAILURE = "GET_ALL_CATEGORY_DATA_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";
