export const COUNTRY_WITH_PHONE_CODE = [
  {
    country: "United States",
    flag: "ðŸ‡ºðŸ‡¸",
    code: "US",
    callingCode: "+1",
  },
  {
    country: "India",
    flag: "ðŸ‡®ðŸ‡³",
    code: "IN",
    callingCode: "+91",
  },
  {
    country: "Afghanistan",
    flag: "ðŸ‡¦ðŸ‡«",
    code: "AF",
    callingCode: "+93",
  },
  {
    country: "Ã…land Islands",
    flag: "ðŸ‡¦ðŸ‡½",
    code: "AX",
    callingCode: "+358",
  },
  {
    country: "Albania",
    flag: "ðŸ‡¦ðŸ‡±",
    code: "AL",
    callingCode: "+355",
  },
  {
    country: "Algeria",
    flag: "ðŸ‡©ðŸ‡¿",
    code: "DZ",
    callingCode: "+213",
  },
  {
    country: "American Samoa",
    flag: "ðŸ‡¦ðŸ‡¸",
    code: "AS",
    callingCode: "+1684",
  },
  {
    country: "Andorra",
    flag: "ðŸ‡¦ðŸ‡©",
    code: "AD",
    callingCode: "+376",
  },
  {
    country: "Angola",
    flag: "ðŸ‡¦ðŸ‡´",
    code: "AO",
    callingCode: "+244",
  },
  {
    country: "Anguilla",
    flag: "ðŸ‡¦ðŸ‡®",
    code: "AI",
    callingCode: "+1264",
  },
  {
    country: "Antarctica",
    flag: "ðŸ‡¦ðŸ‡¶",
    code: "AQ",
    callingCode: "+672",
  },
  {
    country: "Antigua and Barbuda",
    flag: "ðŸ‡¦ðŸ‡¬",
    code: "AG",
    callingCode: "+1268",
  },
  {
    country: "Argentina",
    flag: "ðŸ‡¦ðŸ‡·",
    code: "AR",
    callingCode: "+54",
  },
  {
    country: "Armenia",
    flag: "ðŸ‡¦ðŸ‡²",
    code: "AM",
    callingCode: "+374",
  },
  {
    country: "Aruba",
    flag: "ðŸ‡¦ðŸ‡¼",
    code: "AW",
    callingCode: "+297",
  },
  {
    country: "Australia",
    flag: "ðŸ‡¦ðŸ‡º",
    code: "AU",
    callingCode: "+61",
  },
  {
    country: "Austria",
    flag: "ðŸ‡¦ðŸ‡¹",
    code: "AT",
    callingCode: "+43",
  },
  {
    country: "Azerbaijan",
    flag: "ðŸ‡¦ðŸ‡¿",
    code: "AZ",
    callingCode: "+994",
  },
  {
    country: "Bahamas",
    flag: "ðŸ‡§ðŸ‡¸",
    code: "BS",
    callingCode: "+1242",
  },
  {
    country: "Bahrain",
    flag: "ðŸ‡§ðŸ‡­",
    code: "BH",
    callingCode: "+973",
  },
  {
    country: "Bangladesh",
    flag: "ðŸ‡§ðŸ‡©",
    code: "BD",
    callingCode: "+880",
  },
  {
    country: "Barbados",
    flag: "ðŸ‡§ðŸ‡§",
    code: "BB",
    callingCode: "+1246",
  },
  {
    country: "Belarus",
    flag: "ðŸ‡§ðŸ‡¾",
    code: "BY",
    callingCode: "+375",
  },
  {
    country: "Belgium",
    flag: "ðŸ‡§ðŸ‡ª",
    code: "BE",
    callingCode: "+32",
  },
  {
    country: "Belize",
    flag: "ðŸ‡§ðŸ‡¿",
    code: "BZ",
    callingCode: "+501",
  },
  {
    country: "Benin",
    flag: "ðŸ‡§ðŸ‡¯",
    code: "BJ",
    callingCode: "+229",
  },
  {
    country: "Bermuda",
    flag: "ðŸ‡§ðŸ‡²",
    code: "BM",
    callingCode: "+1441",
  },
  {
    country: "Bhutan",
    flag: "ðŸ‡§ðŸ‡¹",
    code: "BT",
    callingCode: "+975",
  },
  {
    country: "Bolivia, Plurinational State of bolivia",
    flag: "ðŸ‡§ðŸ‡´",
    code: "BO",
    callingCode: "+591",
  },
  {
    country: "Bosnia and Herzegovina",
    flag: "ðŸ‡§ðŸ‡¦",
    code: "BA",
    callingCode: "+387",
  },
  {
    country: "Botswana",
    flag: "ðŸ‡§ðŸ‡¼",
    code: "BW",
    callingCode: "+267",
  },
  {
    country: "Bouvet Island",
    flag: "ðŸ‡§ðŸ‡»",
    code: "BV",
    callingCode: "+47",
  },
  {
    country: "Brazil",
    flag: "ðŸ‡§ðŸ‡·",
    code: "BR",
    callingCode: "+55",
  },
  {
    country: "British Indian Ocean Territory",
    flag: "ðŸ‡®ðŸ‡´",
    code: "IO",
    callingCode: "+246",
  },
  {
    country: "Brunei Darussalam",
    flag: "ðŸ‡§ðŸ‡³",
    code: "BN",
    callingCode: "+673",
  },
  {
    country: "Bulgaria",
    flag: "ðŸ‡§ðŸ‡¬",
    code: "BG",
    callingCode: "+359",
  },
  {
    country: "Burkina Faso",
    flag: "ðŸ‡§ðŸ‡«",
    code: "BF",
    callingCode: "+226",
  },
  {
    country: "Burundi",
    flag: "ðŸ‡§ðŸ‡®",
    code: "BI",
    callingCode: "+257",
  },
  {
    country: "Cambodia",
    flag: "ðŸ‡°ðŸ‡­",
    code: "KH",
    callingCode: "+855",
  },
  {
    country: "Cameroon",
    flag: "ðŸ‡¨ðŸ‡²",
    code: "CM",
    callingCode: "+237",
  },
  {
    country: "Canada",
    flag: "ðŸ‡¨ðŸ‡¦",
    code: "CA",
    callingCode: "+1",
  },
  {
    country: "Cape Verde",
    flag: "ðŸ‡¨ðŸ‡»",
    code: "CV",
    callingCode: "+238",
  },
  {
    country: "Cayman Islands",
    flag: "ðŸ‡°ðŸ‡¾",
    code: "KY",
    callingCode: "+345",
  },
  {
    country: "Central African Republic",
    flag: "ðŸ‡¨ðŸ‡«",
    code: "CF",
    callingCode: "+236",
  },
  {
    country: "Chad",
    flag: "ðŸ‡¹ðŸ‡©",
    code: "TD",
    callingCode: "+235",
  },
  {
    country: "Chile",
    flag: "ðŸ‡¨ðŸ‡±",
    code: "CL",
    callingCode: "+56",
  },
  {
    country: "China",
    flag: "ðŸ‡¨ðŸ‡³",
    code: "CN",
    callingCode: "+86",
  },
  {
    country: "Christmas Island",
    flag: "ðŸ‡¨ðŸ‡½",
    code: "CX",
    callingCode: "+61",
  },
  {
    country: "Cocos (Keeling) Islands",
    flag: "ðŸ‡¨ðŸ‡¨",
    code: "CC",
    callingCode: "+61",
  },
  {
    country: "Colombia",
    flag: "ðŸ‡¨ðŸ‡´",
    code: "CO",
    callingCode: "+57",
  },
  {
    country: "Comoros",
    flag: "ðŸ‡°ðŸ‡²",
    code: "KM",
    callingCode: "+269",
  },
  {
    country: "Congo",
    flag: "ðŸ‡¨ðŸ‡¬",
    code: "CG",
    callingCode: "+242",
  },
  {
    country: "Congo, The Democratic Republic of the Congo",
    flag: "ðŸ‡¨ðŸ‡©",
    code: "CD",
    callingCode: "+243",
  },
  {
    country: "Cook Islands",
    flag: "ðŸ‡¨ðŸ‡°",
    code: "CK",
    callingCode: "+682",
  },
  {
    country: "Costa Rica",
    flag: "ðŸ‡¨ðŸ‡·",
    code: "CR",
    callingCode: "+506",
  },
  {
    country: "Cote d'Ivoire",
    flag: "ðŸ‡¨ðŸ‡®",
    code: "CI",
    callingCode: "+225",
  },
  {
    country: "Croatia",
    flag: "ðŸ‡­ðŸ‡·",
    code: "HR",
    callingCode: "+385",
  },
  {
    country: "Cuba",
    flag: "ðŸ‡¨ðŸ‡º",
    code: "CU",
    callingCode: "+53",
  },
  {
    country: "Cyprus",
    flag: "ðŸ‡¨ðŸ‡¾",
    code: "CY",
    callingCode: "+357",
  },
  {
    country: "Czech Republic",
    flag: "ðŸ‡¨ðŸ‡¿",
    code: "CZ",
    callingCode: "+420",
  },
  {
    country: "Denmark",
    flag: "ðŸ‡©ðŸ‡°",
    code: "DK",
    callingCode: "+45",
  },
  {
    country: "Djibouti",
    flag: "ðŸ‡©ðŸ‡¯",
    code: "DJ",
    callingCode: "+253",
  },
  {
    country: "Dominica",
    flag: "ðŸ‡©ðŸ‡²",
    code: "DM",
    callingCode: "+1767",
  },
  {
    country: "Dominican Republic",
    flag: "ðŸ‡©ðŸ‡´",
    code: "DO",
    callingCode: "+1849",
  },
  {
    country: "Ecuador",
    flag: "ðŸ‡ªðŸ‡¨",
    code: "EC",
    callingCode: "+593",
  },
  {
    country: "Egypt",
    flag: "ðŸ‡ªðŸ‡¬",
    code: "EG",
    callingCode: "+20",
  },
  {
    country: "El Salvador",
    flag: "ðŸ‡¸ðŸ‡»",
    code: "SV",
    callingCode: "+503",
  },
  {
    country: "Equatorial Guinea",
    flag: "ðŸ‡¬ðŸ‡¶",
    code: "GQ",
    callingCode: "+240",
  },
  {
    country: "Eritrea",
    flag: "ðŸ‡ªðŸ‡·",
    code: "ER",
    callingCode: "+291",
  },
  {
    country: "Estonia",
    flag: "ðŸ‡ªðŸ‡ª",
    code: "EE",
    callingCode: "+372",
  },
  {
    country: "Ethiopia",
    flag: "ðŸ‡ªðŸ‡¹",
    code: "ET",
    callingCode: "+251",
  },
  {
    country: "Falkland Islands (Malvinas)",
    flag: "ðŸ‡«ðŸ‡°",
    code: "FK",
    callingCode: "+500",
  },
  {
    country: "Faroe Islands",
    flag: "ðŸ‡«ðŸ‡´",
    code: "FO",
    callingCode: "+298",
  },
  {
    country: "Fiji",
    flag: "ðŸ‡«ðŸ‡¯",
    code: "FJ",
    callingCode: "+679",
  },
  {
    country: "Finland",
    flag: "ðŸ‡«ðŸ‡®",
    code: "FI",
    callingCode: "+358",
  },
  {
    country: "France",
    flag: "ðŸ‡«ðŸ‡·",
    code: "FR",
    callingCode: "+33",
  },
  {
    country: "French Guiana",
    flag: "ðŸ‡¬ðŸ‡«",
    code: "GF",
    callingCode: "+594",
  },
  {
    country: "French Polynesia",
    flag: "ðŸ‡µðŸ‡«",
    code: "PF",
    callingCode: "+689",
  },
  {
    country: "French Southern Territories",
    flag: "ðŸ‡¹ðŸ‡«",
    code: "TF",
    callingCode: "+262",
  },
  {
    country: "Gabon",
    flag: "ðŸ‡¬ðŸ‡¦",
    code: "GA",
    callingCode: "+241",
  },
  {
    country: "Gambia",
    flag: "ðŸ‡¬ðŸ‡²",
    code: "GM",
    callingCode: "+220",
  },
  {
    country: "Georgia",
    flag: "ðŸ‡¬ðŸ‡ª",
    code: "GE",
    callingCode: "+995",
  },
  {
    country: "Germany",
    flag: "ðŸ‡©ðŸ‡ª",
    code: "DE",
    callingCode: "+49",
  },
  {
    country: "Ghana",
    flag: "ðŸ‡¬ðŸ‡­",
    code: "GH",
    callingCode: "+233",
  },
  {
    country: "Gibraltar",
    flag: "ðŸ‡¬ðŸ‡®",
    code: "GI",
    callingCode: "+350",
  },
  {
    country: "Greece",
    flag: "ðŸ‡¬ðŸ‡·",
    code: "GR",
    callingCode: "+30",
  },
  {
    country: "Greenland",
    flag: "ðŸ‡¬ðŸ‡±",
    code: "GL",
    callingCode: "+299",
  },
  {
    country: "Grenada",
    flag: "ðŸ‡¬ðŸ‡©",
    code: "GD",
    callingCode: "+1473",
  },
  {
    country: "Guadeloupe",
    flag: "ðŸ‡¬ðŸ‡µ",
    code: "GP",
    callingCode: "+590",
  },
  {
    country: "Guam",
    flag: "ðŸ‡¬ðŸ‡º",
    code: "GU",
    callingCode: "+1671",
  },
  {
    country: "Guatemala",
    flag: "ðŸ‡¬ðŸ‡¹",
    code: "GT",
    callingCode: "+502",
  },
  {
    country: "Guernsey",
    flag: "ðŸ‡¬ðŸ‡¬",
    code: "GG",
    callingCode: "+44",
  },
  {
    country: "Guinea",
    flag: "ðŸ‡¬ðŸ‡³",
    code: "GN",
    callingCode: "+224",
  },
  {
    country: "Guinea-Bissau",
    flag: "ðŸ‡¬ðŸ‡¼",
    code: "GW",
    callingCode: "+245",
  },
  {
    country: "Guyana",
    flag: "ðŸ‡¬ðŸ‡¾",
    code: "GY",
    callingCode: "+592",
  },
  {
    country: "Haiti",
    flag: "ðŸ‡­ðŸ‡¹",
    code: "HT",
    callingCode: "+509",
  },
  {
    country: "Heard Island and Mcdonald Islands",
    flag: "ðŸ‡­ðŸ‡²",
    code: "HM",
    callingCode: "+672",
  },
  {
    country: "Holy See (Vatican City State)",
    flag: "ðŸ‡»ðŸ‡¦",
    code: "VA",
    callingCode: "+379",
  },
  {
    country: "Honduras",
    flag: "ðŸ‡­ðŸ‡³",
    code: "HN",
    callingCode: "+504",
  },
  {
    country: "Hong Kong",
    flag: "ðŸ‡­ðŸ‡°",
    code: "HK",
    callingCode: "+852",
  },
  {
    country: "Hungary",
    flag: "ðŸ‡­ðŸ‡º",
    code: "HU",
    callingCode: "+36",
  },
  {
    country: "Iceland",
    flag: "ðŸ‡®ðŸ‡¸",
    code: "IS",
    callingCode: "+354",
  },
  {
    country: "Indonesia",
    flag: "ðŸ‡®ðŸ‡©",
    code: "ID",
    callingCode: "+62",
  },
  {
    country: "Iran, Islamic Republic of Persian Gulf",
    flag: "ðŸ‡®ðŸ‡·",
    code: "IR",
    callingCode: "+98",
  },
  {
    country: "Iraq",
    flag: "ðŸ‡®ðŸ‡¶",
    code: "IQ",
    callingCode: "+964",
  },
  {
    country: "Ireland",
    flag: "ðŸ‡®ðŸ‡ª",
    code: "IE",
    callingCode: "+353",
  },
  {
    country: "Isle of Man",
    flag: "ðŸ‡®ðŸ‡²",
    code: "IM",
    callingCode: "+44",
  },
  {
    country: "Israel",
    flag: "ðŸ‡®ðŸ‡±",
    code: "IL",
    callingCode: "+972",
  },
  {
    country: "Italy",
    flag: "ðŸ‡®ðŸ‡¹",
    code: "IT",
    callingCode: "+39",
  },
  {
    country: "Jamaica",
    flag: "ðŸ‡¯ðŸ‡²",
    code: "JM",
    callingCode: "+1876",
  },
  {
    country: "Japan",
    flag: "ðŸ‡¯ðŸ‡µ",
    code: "JP",
    callingCode: "+81",
  },
  {
    country: "Jersey",
    flag: "ðŸ‡¯ðŸ‡ª",
    code: "JE",
    callingCode: "+44",
  },
  {
    country: "Jordan",
    flag: "ðŸ‡¯ðŸ‡´",
    code: "JO",
    callingCode: "+962",
  },
  {
    country: "Kazakhstan",
    flag: "ðŸ‡°ðŸ‡¿",
    code: "KZ",
    callingCode: "+7",
  },
  {
    country: "Kenya",
    flag: "ðŸ‡°ðŸ‡ª",
    code: "KE",
    callingCode: "+254",
  },
  {
    country: "Kiribati",
    flag: "ðŸ‡°ðŸ‡®",
    code: "KI",
    callingCode: "+686",
  },
  {
    country: "Korea, Democratic People's Republic of Korea",
    flag: "ðŸ‡°ðŸ‡µ",
    code: "KP",
    callingCode: "+850",
  },
  {
    country: "Korea, Republic of South Korea",
    flag: "ðŸ‡°ðŸ‡·",
    code: "KR",
    callingCode: "+82",
  },
  {
    country: "Kosovo",
    flag: "ðŸ‡½ðŸ‡°",
    code: "XK",
    callingCode: "+383",
  },
  {
    country: "Kuwait",
    flag: "ðŸ‡°ðŸ‡¼",
    code: "KW",
    callingCode: "+965",
  },
  {
    country: "Kyrgyzstan",
    flag: "ðŸ‡°ðŸ‡¬",
    code: "KG",
    callingCode: "+996",
  },
  {
    country: "Laos",
    flag: "ðŸ‡±ðŸ‡¦",
    code: "LA",
    callingCode: "+856",
  },
  {
    country: "Latvia",
    flag: "ðŸ‡±ðŸ‡»",
    code: "LV",
    callingCode: "+371",
  },
  {
    country: "Lebanon",
    flag: "ðŸ‡±ðŸ‡§",
    code: "LB",
    callingCode: "+961",
  },
  {
    country: "Lesotho",
    flag: "ðŸ‡±ðŸ‡¸",
    code: "LS",
    callingCode: "+266",
  },
  {
    country: "Liberia",
    flag: "ðŸ‡±ðŸ‡·",
    code: "LR",
    callingCode: "+231",
  },
  {
    country: "Libyan Arab Jamahiriya",
    flag: "ðŸ‡±ðŸ‡¾",
    code: "LY",
    callingCode: "+218",
  },
  {
    country: "Liechtenstein",
    flag: "ðŸ‡±ðŸ‡®",
    code: "LI",
    callingCode: "+423",
  },
  {
    country: "Lithuania",
    flag: "ðŸ‡±ðŸ‡¹",
    code: "LT",
    callingCode: "+370",
  },
  {
    country: "Luxembourg",
    flag: "ðŸ‡±ðŸ‡º",
    code: "LU",
    callingCode: "+352",
  },
  {
    country: "Macao",
    flag: "ðŸ‡²ðŸ‡´",
    code: "MO",
    callingCode: "+853",
  },
  {
    country: "Macedonia",
    flag: "ðŸ‡²ðŸ‡°",
    code: "MK",
    callingCode: "+389",
  },
  {
    country: "Madagascar",
    flag: "ðŸ‡²ðŸ‡¬",
    code: "MG",
    callingCode: "+261",
  },
  {
    country: "Malawi",
    flag: "ðŸ‡²ðŸ‡¼",
    code: "MW",
    callingCode: "+265",
  },
  {
    country: "Malaysia",
    flag: "ðŸ‡²ðŸ‡¾",
    code: "MY",
    callingCode: "+60",
  },
  {
    country: "Maldives",
    flag: "ðŸ‡²ðŸ‡»",
    code: "MV",
    callingCode: "+960",
  },
  {
    country: "Mali",
    flag: "ðŸ‡²ðŸ‡±",
    code: "ML",
    callingCode: "+223",
  },
  {
    country: "Malta",
    flag: "ðŸ‡²ðŸ‡¹",
    code: "MT",
    callingCode: "+356",
  },
  {
    country: "Marshall Islands",
    flag: "ðŸ‡²ðŸ‡­",
    code: "MH",
    callingCode: "+692",
  },
  {
    country: "Martinique",
    flag: "ðŸ‡²ðŸ‡¶",
    code: "MQ",
    callingCode: "+596",
  },
  {
    country: "Mauritania",
    flag: "ðŸ‡²ðŸ‡·",
    code: "MR",
    callingCode: "+222",
  },
  {
    country: "Mauritius",
    flag: "ðŸ‡²ðŸ‡º",
    code: "MU",
    callingCode: "+230",
  },
  {
    country: "Mayotte",
    flag: "ðŸ‡¾ðŸ‡¹",
    code: "YT",
    callingCode: "+262",
  },
  {
    country: "Mexico",
    flag: "ðŸ‡²ðŸ‡½",
    code: "MX",
    callingCode: "+52",
  },
  {
    country: "Micronesia, Federated States of Micronesia",
    flag: "ðŸ‡«ðŸ‡²",
    code: "FM",
    callingCode: "+691",
  },
  {
    country: "Moldova",
    flag: "ðŸ‡²ðŸ‡©",
    code: "MD",
    callingCode: "+373",
  },
  {
    country: "Monaco",
    flag: "ðŸ‡²ðŸ‡¨",
    code: "MC",
    callingCode: "+377",
  },
  {
    country: "Mongolia",
    flag: "ðŸ‡²ðŸ‡³",
    code: "MN",
    callingCode: "+976",
  },
  {
    country: "Montenegro",
    flag: "ðŸ‡²ðŸ‡ª",
    code: "ME",
    callingCode: "+382",
  },
  {
    country: "Montserrat",
    flag: "ðŸ‡²ðŸ‡¸",
    code: "MS",
    callingCode: "+1664",
  },
  {
    country: "Morocco",
    flag: "ðŸ‡²ðŸ‡¦",
    code: "MA",
    callingCode: "+212",
  },
  {
    country: "Mozambique",
    flag: "ðŸ‡²ðŸ‡¿",
    code: "MZ",
    callingCode: "+258",
  },
  {
    country: "Myanmar",
    flag: "ðŸ‡²ðŸ‡²",
    code: "MM",
    callingCode: "+95",
  },
  {
    country: "Namibia",
    flag: "ðŸ‡³ðŸ‡¦",
    code: "NA",
    callingCode: "+264",
  },
  {
    country: "Nauru",
    flag: "ðŸ‡³ðŸ‡·",
    code: "NR",
    callingCode: "+674",
  },
  {
    country: "Nepal",
    flag: "ðŸ‡³ðŸ‡µ",
    code: "NP",
    callingCode: "+977",
  },
  {
    country: "Netherlands",
    flag: "ðŸ‡³ðŸ‡±",
    code: "NL",
    callingCode: "+31",
  },
  {
    country: "Netherlands Antilles",
    flag: "",
    code: "AN",
    callingCode: "+599",
  },
  {
    country: "New Caledonia",
    flag: "ðŸ‡³ðŸ‡¨",
    code: "NC",
    callingCode: "+687",
  },
  {
    country: "New Zealand",
    flag: "ðŸ‡³ðŸ‡¿",
    code: "NZ",
    callingCode: "+64",
  },
  {
    country: "Nicaragua",
    flag: "ðŸ‡³ðŸ‡®",
    code: "NI",
    callingCode: "+505",
  },
  {
    country: "Niger",
    flag: "ðŸ‡³ðŸ‡ª",
    code: "NE",
    callingCode: "+227",
  },
  {
    country: "Nigeria",
    flag: "ðŸ‡³ðŸ‡¬",
    code: "NG",
    callingCode: "+234",
  },
  {
    country: "Niue",
    flag: "ðŸ‡³ðŸ‡º",
    code: "NU",
    callingCode: "+683",
  },
  {
    country: "Norfolk Island",
    flag: "ðŸ‡³ðŸ‡«",
    code: "NF",
    callingCode: "+672",
  },
  {
    country: "Northern Mariana Islands",
    flag: "ðŸ‡²ðŸ‡µ",
    code: "MP",
    callingCode: "+1670",
  },
  {
    country: "Norway",
    flag: "ðŸ‡³ðŸ‡´",
    code: "NO",
    callingCode: "+47",
  },
  {
    country: "Oman",
    flag: "ðŸ‡´ðŸ‡²",
    code: "OM",
    callingCode: "+968",
  },
  {
    country: "Pakistan",
    flag: "ðŸ‡µðŸ‡°",
    code: "PK",
    callingCode: "+92",
  },
  {
    country: "Palau",
    flag: "ðŸ‡µðŸ‡¼",
    code: "PW",
    callingCode: "+680",
  },
  {
    country: "Palestinian Territory, Occupied",
    flag: "ðŸ‡µðŸ‡¸",
    code: "PS",
    callingCode: "+970",
  },
  {
    country: "Panama",
    flag: "ðŸ‡µðŸ‡¦",
    code: "PA",
    callingCode: "+507",
  },
  {
    country: "Papua New Guinea",
    flag: "ðŸ‡µðŸ‡¬",
    code: "PG",
    callingCode: "+675",
  },
  {
    country: "Paraguay",
    flag: "ðŸ‡µðŸ‡¾",
    code: "PY",
    callingCode: "+595",
  },
  {
    country: "Peru",
    flag: "ðŸ‡µðŸ‡ª",
    code: "PE",
    callingCode: "+51",
  },
  {
    country: "Philippines",
    flag: "ðŸ‡µðŸ‡­",
    code: "PH",
    callingCode: "+63",
  },
  {
    country: "Pitcairn",
    flag: "ðŸ‡µðŸ‡³",
    code: "PN",
    callingCode: "+64",
  },
  {
    country: "Poland",
    flag: "ðŸ‡µðŸ‡±",
    code: "PL",
    callingCode: "+48",
  },
  {
    country: "Portugal",
    flag: "ðŸ‡µðŸ‡¹",
    code: "PT",
    callingCode: "+351",
  },
  {
    country: "Puerto Rico",
    flag: "ðŸ‡µðŸ‡·",
    code: "PR",
    callingCode: "+1939",
  },
  {
    country: "Qatar",
    flag: "ðŸ‡¶ðŸ‡¦",
    code: "QA",
    callingCode: "+974",
  },
  {
    country: "Romania",
    flag: "ðŸ‡·ðŸ‡´",
    code: "RO",
    callingCode: "+40",
  },
  {
    country: "Russia",
    flag: "ðŸ‡·ðŸ‡º",
    code: "RU",
    callingCode: "+7",
  },
  {
    country: "Rwanda",
    flag: "ðŸ‡·ðŸ‡¼",
    code: "RW",
    callingCode: "+250",
  },
  {
    country: "Reunion",
    flag: "ðŸ‡·ðŸ‡ª",
    code: "RE",
    callingCode: "+262",
  },
  {
    country: "Saint Barthelemy",
    flag: "ðŸ‡§ðŸ‡±",
    code: "BL",
    callingCode: "+590",
  },
  {
    country: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "ðŸ‡¸ðŸ‡­",
    code: "SH",
    callingCode: "+290",
  },
  {
    country: "Saint Kitts and Nevis",
    flag: "ðŸ‡°ðŸ‡³",
    code: "KN",
    callingCode: "+1869",
  },
  {
    country: "Saint Lucia",
    flag: "ðŸ‡±ðŸ‡¨",
    code: "LC",
    callingCode: "+1758",
  },
  {
    country: "Saint Martin",
    flag: "ðŸ‡²ðŸ‡«",
    code: "MF",
    callingCode: "+590",
  },
  {
    country: "Saint Pierre and Miquelon",
    flag: "ðŸ‡µðŸ‡²",
    code: "PM",
    callingCode: "+508",
  },
  {
    country: "Saint Vincent and the Grenadines",
    flag: "ðŸ‡»ðŸ‡¨",
    code: "VC",
    callingCode: "+1784",
  },
  {
    country: "Samoa",
    flag: "ðŸ‡¼ðŸ‡¸",
    code: "WS",
    callingCode: "+685",
  },
  {
    country: "San Marino",
    flag: "ðŸ‡¸ðŸ‡²",
    code: "SM",
    callingCode: "+378",
  },
  {
    country: "Sao Tome and Principe",
    flag: "ðŸ‡¸ðŸ‡¹",
    code: "ST",
    callingCode: "+239",
  },
  {
    country: "Saudi Arabia",
    flag: "ðŸ‡¸ðŸ‡¦",
    code: "SA",
    callingCode: "+966",
  },
  {
    country: "Senegal",
    flag: "ðŸ‡¸ðŸ‡³",
    code: "SN",
    callingCode: "+221",
  },
  {
    country: "Serbia",
    flag: "ðŸ‡·ðŸ‡¸",
    code: "RS",
    callingCode: "+381",
  },
  {
    country: "Seychelles",
    flag: "ðŸ‡¸ðŸ‡¨",
    code: "SC",
    callingCode: "+248",
  },
  {
    country: "Sierra Leone",
    flag: "ðŸ‡¸ðŸ‡±",
    code: "SL",
    callingCode: "+232",
  },
  {
    country: "Singapore",
    flag: "ðŸ‡¸ðŸ‡¬",
    code: "SG",
    callingCode: "+65",
  },
  {
    country: "Slovakia",
    flag: "ðŸ‡¸ðŸ‡°",
    code: "SK",
    callingCode: "+421",
  },
  {
    country: "Slovenia",
    flag: "ðŸ‡¸ðŸ‡®",
    code: "SI",
    callingCode: "+386",
  },
  {
    country: "Solomon Islands",
    flag: "ðŸ‡¸ðŸ‡§",
    code: "SB",
    callingCode: "+677",
  },
  {
    country: "Somalia",
    flag: "ðŸ‡¸ðŸ‡´",
    code: "SO",
    callingCode: "+252",
  },
  {
    country: "South Africa",
    flag: "ðŸ‡¿ðŸ‡¦",
    code: "ZA",
    callingCode: "+27",
  },
  {
    country: "South Sudan",
    flag: "ðŸ‡¸ðŸ‡¸",
    code: "SS",
    callingCode: "+211",
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    flag: "ðŸ‡¬ðŸ‡¸",
    code: "GS",
    callingCode: "+500",
  },
  {
    country: "Spain",
    flag: "ðŸ‡ªðŸ‡¸",
    code: "ES",
    callingCode: "+34",
  },
  {
    country: "Sri Lanka",
    flag: "ðŸ‡±ðŸ‡°",
    code: "LK",
    callingCode: "+94",
  },
  {
    country: "Sudan",
    flag: "ðŸ‡¸ðŸ‡©",
    code: "SD",
    callingCode: "+249",
  },
  {
    country: "Suriname",
    flag: "ðŸ‡¸ðŸ‡·",
    code: "SR",
    callingCode: "+597",
  },
  {
    country: "Svalbard and Jan Mayen",
    flag: "ðŸ‡¸ðŸ‡¯",
    code: "SJ",
    callingCode: "+47",
  },
  {
    country: "Swaziland",
    flag: "ðŸ‡¸ðŸ‡¿",
    code: "SZ",
    callingCode: "+268",
  },
  {
    country: "Sweden",
    flag: "ðŸ‡¸ðŸ‡ª",
    code: "SE",
    callingCode: "+46",
  },
  {
    country: "Switzerland",
    flag: "ðŸ‡¨ðŸ‡­",
    code: "CH",
    callingCode: "+41",
  },
  {
    country: "Syrian Arab Republic",
    flag: "ðŸ‡¸ðŸ‡¾",
    code: "SY",
    callingCode: "+963",
  },
  {
    country: "Taiwan",
    flag: "ðŸ‡¹ðŸ‡¼",
    code: "TW",
    callingCode: "+886",
  },
  {
    country: "Tajikistan",
    flag: "ðŸ‡¹ðŸ‡¯",
    code: "TJ",
    callingCode: "+992",
  },
  {
    country: "Tanzania, United Republic of Tanzania",
    flag: "ðŸ‡¹ðŸ‡¿",
    code: "TZ",
    callingCode: "+255",
  },
  {
    country: "Thailand",
    flag: "ðŸ‡¹ðŸ‡­",
    code: "TH",
    callingCode: "+66",
  },
  {
    country: "Timor-Leste",
    flag: "ðŸ‡¹ðŸ‡±",
    code: "TL",
    callingCode: "+670",
  },
  {
    country: "Togo",
    flag: "ðŸ‡¹ðŸ‡¬",
    code: "TG",
    callingCode: "+228",
  },
  {
    country: "Tokelau",
    flag: "ðŸ‡¹ðŸ‡°",
    code: "TK",
    callingCode: "+690",
  },
  {
    country: "Tonga",
    flag: "ðŸ‡¹ðŸ‡´",
    code: "TO",
    callingCode: "+676",
  },
  {
    country: "Trinidad and Tobago",
    flag: "ðŸ‡¹ðŸ‡¹",
    code: "TT",
    callingCode: "+1868",
  },
  {
    country: "Tunisia",
    flag: "ðŸ‡¹ðŸ‡³",
    code: "TN",
    callingCode: "+216",
  },
  {
    country: "Turkey",
    flag: "ðŸ‡¹ðŸ‡·",
    code: "TR",
    callingCode: "+90",
  },
  {
    country: "Turkmenistan",
    flag: "ðŸ‡¹ðŸ‡²",
    code: "TM",
    callingCode: "+993",
  },
  {
    country: "Turks and Caicos Islands",
    flag: "ðŸ‡¹ðŸ‡¨",
    code: "TC",
    callingCode: "+1649",
  },
  {
    country: "Tuvalu",
    flag: "ðŸ‡¹ðŸ‡»",
    code: "TV",
    callingCode: "+688",
  },
  {
    country: "Uganda",
    flag: "ðŸ‡ºðŸ‡¬",
    code: "UG",
    callingCode: "+256",
  },
  {
    country: "Ukraine",
    flag: "ðŸ‡ºðŸ‡¦",
    code: "UA",
    callingCode: "+380",
  },
  {
    country: "United Arab Emirates",
    flag: "ðŸ‡¦ðŸ‡ª",
    code: "AE",
    callingCode: "+971",
  },
  {
    country: "United Kingdom",
    flag: "ðŸ‡¬ðŸ‡§",
    code: "GB",
    callingCode: "+44",
  },
  {
    country: "Uruguay",
    flag: "ðŸ‡ºðŸ‡¾",
    code: "UY",
    callingCode: "+598",
  },
  {
    country: "Uzbekistan",
    flag: "ðŸ‡ºðŸ‡¿",
    code: "UZ",
    callingCode: "+998",
  },
  {
    country: "Vanuatu",
    flag: "ðŸ‡»ðŸ‡º",
    code: "VU",
    callingCode: "+678",
  },
  {
    country: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "ðŸ‡»ðŸ‡ª",
    code: "VE",
    callingCode: "+58",
  },
  {
    country: "Vietnam",
    flag: "ðŸ‡»ðŸ‡³",
    code: "VN",
    callingCode: "+84",
  },
  {
    country: "Virgin Islands, British",
    flag: "ðŸ‡»ðŸ‡¬",
    code: "VG",
    callingCode: "+1284",
  },
  {
    country: "Virgin Islands, U.S.",
    flag: "ðŸ‡»ðŸ‡®",
    code: "VI",
    callingCode: "+1340",
  },
  {
    country: "Wallis and Futuna",
    flag: "ðŸ‡¼ðŸ‡«",
    code: "WF",
    callingCode: "+681",
  },
  {
    country: "Yemen",
    flag: "ðŸ‡¾ðŸ‡ª",
    code: "YE",
    callingCode: "+967",
  },
  {
    country: "Zambia",
    flag: "ðŸ‡¿ðŸ‡²",
    code: "ZM",
    callingCode: "+260",
  },
  {
    country: "Zimbabwe",
    flag: "ðŸ‡¿ðŸ‡¼",
    code: "ZW",
    callingCode: "+263",
  },
];
